# Generated by Django 4.0.3 on 2024-01-22 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TbAdmin',
            fields=[
                ('user_id', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('user_pw', models.CharField(blank=True, max_length=45, null=True)),
                ('branch', models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                'db_table': 'tb_admin',
                'managed': False,
            },
        ),
    ]
